name: My Basic Pipeline

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
              python-version: 3.11

        - name: Install Poetry
          uses: snok/install-poetry@v1

        - name: Install dependencies
          run: |
              echo "Installing dependencies"
              poetry install

        - name: Deploy
          run: |
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
